### ISSUE TITLE
404 after installing plugin

### ISSUE THREAD

**Issue by jredl-va** [teamclairvoyant/airflow-rest-api-plugin#1]
Greetings,

I was pretty excited to come across this plugin, however unfortunately I'm receiving a 404 after installing the plugin and attempting to hit any of the routes. I've verified the plugin exists within the plugins folder and have rebooted the server:

```
| /home/airflow/plugins
|-- rest_api_plugin.py
|-- templates
```

I'm currently running on an RC version 1.8.0. Is there anything else that needs to occur to enable this?

**Comment by rssanders3** [comment]
Hello,

Within your airflow.cfg file is the plugins_folder property set to "/home/airflow/plugins" or something else? The value of that property setting would be the location to put all of the plugin files (rest_api_plugin.py and templates). If airflow is the user, by default, the plugins directory would usually be at /home/airflow/airflow/plugins. This is because /home/airflow would be the users home directory. Under there would be an airflow directory with all of airflows configs and subdirectories (which include the plugins directory).

Do you see any errors or anything in the web server logs regarding the rest api plugin?

I also built it testing it on 1.7.X Versions of Airflow since those were the official releases. I'll try it out on RC version 1.8.0. Is this the version you're running it on: https://github.com/apache/incubator-airflow/tree/v1-8-stable?

**Comment by jredl-va** [comment]
It is indeed, looking at this with fresh eyes I realized I was in race condition syncing my plugins to the webserver. It turns out everything is working fine on 1.8 and this is purely user error!

**Comment by jredl-va** [comment]
p.s. Thanks for the community contribution! This api makes airflow much more usable for our use case.

**Comment by rssanders3** [comment]
Ok glad to hear you were able to resolve this. I'm glad this helps your use case so well. Let us know if you come across any other issues! :)
