### ISSUE TITLE
Integration with official Airflow project

### ISSUE THREAD

**Issue by yono38** [teamclairvoyant/airflow-rest-api-plugin#16]
Hey, I wanted to thank you for the work you have put into this plugin, it adds a lot of great functionality to allow us to control airflow without needing direct control over the GUI or CLI!

I saw that the Apache team has started work on their own REST capabilities ( [docs](http://airflow.incubator.apache.org/api.html) / [source](https://github.com/apache/incubator-airflow/blob/master/airflow/www/api/experimental/endpoints.py) ), but that you are far ahead of them in terms of functionality.

I was wondering what your intentions were for moving forward on this. Would you prefer to stay as a separate plugin (giving you more freedom) or are you interested in collaborating with the official team to integrate your work into the official build? (Note: I'm not associated with the apache team, just a consumer of Airflow in my work)

**Comment by rssanders3** [comment]
Yup thats correct that the Apache Airflow Dev team has started to build out REST capabilities but their not completely there yet. 

My intention for right now is to continue to support this REST API plugin until the official Airflow REST API is ready for prime time since I do think that having a REST API is a very valuable feature. So this project will remain independent of their code base and serve as an option. 

However, as soon as this project is 99% bug free and provides all the features that the community requires, I do want to start to contribute to that project and build out that REST API feature. I'm not sure when I will have time for this. But I hope to start that in the next couple months.

In the meantime, if you have any requirements that this plugin doesn't fulfill, let me know or feel free to add them and merge back.

Thanks for reaching out.
