### ISSUE TITLE
API is getting timed-out 

### ISSUE THREAD

**Issue by bendrya** [teamclairvoyant/airflow-rest-api-plugin#18]
I'm trying to pause a DAG with an API call. The"pause" action is working but after that, the API gets timed out and a blank response is received after the timeout. 

API Version: 1.0.4
Airflow Version: 1.8.0

We tried other APIs and they are getting timed out as well. API Version 1.0.3 had the same issue as well and upgrading to 1.0.4 has not fixed it. We also tried this with and without token authentication but the behaviour is the same in both cases. 

When we tried calling the "pause" API without the "dag_id" parameters, it throws the appropriate error saying that the required parameters (dag_id in this case) are missing.

**Comment by ozw1z5rd** [comment]
I got something like you and found that the execute_cli_command() is using the Popen.wait(), which can **deadlock**, see [the comment](https://docs.python.org/3/library/subprocess.html#popen-objects) on the documentation. I solved replacing it with Popen.communicate() as suggested.

**Comment by bendrya** [comment]
Thanks ozw1z5rd! 

Our team has identified the same issue with `.wait()` and timeout problem was resolved after replacing it with `.communicate()`. The pipe output size was significantly large causing the deadlock.

**Comment by aravindboppana** [comment]
Hello Bendrya
I have tried replicating the issue. Using 
API Version: 1.0.4
Airflow Version: 1.8.0
Tried out all the APIs.They are working fine for me.Pipe output size will get significantly large when the output or error produced by the command that we are running is very big. But the commands that we are running to pause, unpause etc doesn't produce a large output.

Can you provide me with other details if you think I am missing any so that I can replicate the issue?

**Comment by mpasa** [comment]
We are getting to the same problem. The output of the Airflow cmd is not that big, but it seems to get stuck using `wait()`. We solved the problem using:

```
(out, err) = process.communicate()
return {
    "stderr": err.decode("utf-8"),
    "stdin": "",
    "stdout": out.decode("utf-8")
}
```

instead of

```
process.wait()
 return REST_API.collect_process_output(process)
```

It works as expected for us, but we're losing the `stdin` part. I'm not sure that part is used though. Do you think we could merge this?
