### ISSUE TITLE
REST API menu is not on dashboard and API throws 403 error

### ISSUE THREAD

**Issue by jainikpurohit** [teamclairvoyant/airflow-rest-api-plugin#44]
First of all, thank you for creating this. It is an ideal match for our use case.
I followed the documentation to add this as a plugin to my local airflow instance but having trouble with accessing endpoints.

Rest API menu item under Admin does not appear for some reason but even when I tried to run URL directly, received an error as below:

> Forbidden
> You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

I did not enable any authentication part in the config file and using v1.0.6 release for the plugin.

**Comment by rssanders3** [comment]
Hello @jainikpurohit, thanks for letting us know of this issue. This is due to a recent change where we're trying to fix a security hole where users, if not authenticated, can still submit REST API requests. We're working on coming up with a more permanent fix (which will be in release 1.0.7), but for now, to get past this issue, you can **comment out** the functions at line number 516 (https://github.com/teamclairvoyant/airflow-rest-api-plugin/blob/v1.0.7-branch/plugins/rest_api_plugin.py#L516) and 520 (https://github.com/teamclairvoyant/airflow-rest-api-plugin/blob/v1.0.7-branch/plugins/rest_api_plugin.py#L520) in the rest_api_plugin.py file. these functions:

    # overrides BaseView method to show/hide the menu links dynamically
    def is_visible(self):
        return current_user.is_authenticated

    # overrides BaseView method to check permission for the menu link
    def is_accessible(self):
        return current_user.is_authenticated

**Comment by jainikpurohit** [comment]
Thank You @rssanders3 for the workaround. It worked and I can see things working now. I would prefer to keep the issue open until we have a permanent fix ready so that other users do not open the same issue and can find their answer easily.

**Comment by sudhakar-nallam** [comment]
This issue is resolved in #48
